INSERT INTO APPLICATION_STATE (ID, APP_TEXT)
                       VALUES (1, 'INITIAL');
INSERT INTO APPLICATION_STATE (ID, APP_TEXT)
                       VALUES (2, 'CREATED');
INSERT INTO APPLICATION_STATE (ID, APP_TEXT)
                       VALUES (3, 'DOCTOR_ASSIGNED');
INSERT INTO APPLICATION_STATE (ID, APP_TEXT)
                       VALUES (4, 'HEALTH_STATUS_OK');
INSERT INTO APPLICATION_STATE (ID, APP_TEXT)
                       VALUES (5, 'CONTRACT_OFFERED');
INSERT INTO APPLICATION_STATE (ID, APP_TEXT)
                       VALUES (6, 'CLIENT_AGREED');
INSERT INTO APPLICATION_STATE (ID, APP_TEXT)
                       VALUES (7, 'CLIENT_REGISTERED');
INSERT INTO APPLICATION_STATE (ID, APP_TEXT)
                       VALUES (8, 'COACH_REQUESTED');
INSERT INTO APPLICATION_STATE (ID, APP_TEXT)
                       VALUES (9, 'FORM_OFFERED');
INSERT INTO APPLICATION_STATE (ID, APP_TEXT)
                       VALUES (10, 'FORM_FILLED');
INSERT INTO APPLICATION_STATE (ID, APP_TEXT)
                       VALUES (11, 'PROGRAM_ASSIGNED');

COMMIT;
